### PR TITLE
Update Guzzle 6.2.2

### PR DESCRIPTION
**Pull request by baona95**
I haven't tested it properly because it require guzzle 5.3. But it should work I think.

Base on the document http://docs.guzzlephp.org/en/latest/ and what I have done in other projects.

### CODE REVIEW

**Comment by michelecurletta** [comment]
Hi @trandaihung, could you please test this update properly? Thanks

**Comment by trandaihung** [comment]
It would help if you change the guzzle version to ^6.0.
This is not a stand-alone library so it is really hard for me to require the package via composer because of requirements conflict.

**Comment by trandaihung** [comment]
I've tested and fixed one issue with the relative path. It should work.

Please update the guzzle version to ^6.2 on your own.

**Comment by weotch** [comment]
+1 for merge

**Pull request merged**
